In [1]:
import numpy as np

In [3]:
# batch2
list_of_objects2 = [
    "107-a_pepsi_bottle",
    "107-b_pepsi_bottle",
    "107-c_pepsi_bottle",
    "107-d_pepsi_bottle",
    "107-e_pepsi_bottle",
    "108-a_tuna_fish_can",
    "108-b_tuna_fish_can",
    "108-c_tuna_fish_can",
    "108-d_tuna_fish_can",
    "108-e_tuna_fish_can",
    "109-a_soymilk",
    "109-b_soymilk",
    "109-c_soymilk",
    "109-d_soymilk",
    "109-e_soymilk",
    "110-a_coffee_can",
    "110-b_coffee_can",
    "110-c_coffee_can",
    "110-d_coffee_can",
    "110-e_coffee_can",
]

In [25]:
# create labels
labels = []
current_label = -1
overall_count = 14

e = 1

for obj in list_of_objects2:
    current_label += 1
    
    for i in range(15, 15+20, 1):
        overall_count+=1
        labels.append([overall_count, current_label])
    overall_count += 20
    e+=1
labels = np.array(labels)

In [26]:
labels

array([[ 15,   0],
       [ 16,   0],
       [ 17,   0],
       [ 18,   0],
       [ 19,   0],
       [ 20,   0],
       [ 21,   0],
       [ 22,   0],
       [ 23,   0],
       [ 24,   0],
       [ 25,   0],
       [ 26,   0],
       [ 27,   0],
       [ 28,   0],
       [ 29,   0],
       [ 30,   0],
       [ 31,   0],
       [ 32,   0],
       [ 33,   0],
       [ 34,   0],
       [ 55,   1],
       [ 56,   1],
       [ 57,   1],
       [ 58,   1],
       [ 59,   1],
       [ 60,   1],
       [ 61,   1],
       [ 62,   1],
       [ 63,   1],
       [ 64,   1],
       [ 65,   1],
       [ 66,   1],
       [ 67,   1],
       [ 68,   1],
       [ 69,   1],
       [ 70,   1],
       [ 71,   1],
       [ 72,   1],
       [ 73,   1],
       [ 74,   1],
       [ 95,   2],
       [ 96,   2],
       [ 97,   2],
       [ 98,   2],
       [ 99,   2],
       [100,   2],
       [101,   2],
       [102,   2],
       [103,   2],
       [104,   2],
       [105,   2],
       [106,   2],
       [107,

In [27]:
from sklearn.model_selection import StratifiedKFold

In [28]:
# stratified k fold
skf = StratifiedKFold(n_splits=5, random_state=100, shuffle=True)
train_indices = []
test_indices = []

In [29]:
for train_index, test_index in  skf.split(np.zeros(len(labels)), labels[:,1]):
    train_indices.append(train_index)
    test_indices.append(test_index)
    print("TRAIN:", train_index, "TEST:", test_index)

TRAIN: [  0   1   2   3   4   5   6   7   8   9  10  12  13  14  15  16  21  22
  23  24  25  26  27  28  29  30  31  32  33  34  35  36  40  41  42  45
  46  47  48  49  50  51  53  54  55  56  58  59  60  62  63  64  66  67
  68  69  70  71  72  73  74  77  78  79  80  81  82  84  85  86  87  89
  90  91  92  93  94  95  96  98 100 102 103 104 105 106 107 108 109 110
 112 113 114 117 118 119 120 121 122 123 124 125 126 129 130 131 132 133
 134 137 138 139 140 142 143 144 145 146 148 149 150 152 153 154 156 157
 158 159 160 161 162 163 164 165 166 167 168 170 173 174 175 176 177 179
 180 181 182 183 184 185 186 187 190 191 192 193 195 197 198 199 200 201
 202 203 204 205 206 207 209 210 212 213 214 215 216 217 220 221 222 223
 225 226 227 228 229 232 233 234 236 237 238 239 242 243 244 245 246 247
 248 249 251 252 253 254 255 257 258 259 260 261 263 264 265 266 267 268
 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 289 290
 292 293 294 295 297 298 300 301 305 307 308

In [42]:
save_dir = '../data_VT_SNN_2/'

In [43]:
# write to the file
splits = ['80_20_6','80_20_7','80_20_8','80_20_9', '80_20_10']
count = 0
for split in splits:
    tr = labels[train_indices[count], :]
    np.random.shuffle(tr)
    np.savetxt(save_dir + 'train_' + split + '.txt', np.array(tr, dtype=int), fmt='%d', delimiter='\t')
    np.savetxt(save_dir + 'test_' + split + '.txt', np.array(labels[test_indices[count], :], dtype=int), fmt='%d', delimiter='\t')
    count += 1

In [31]:
labels[train_indices[0], :]

array([[ 15,   0],
       [ 16,   0],
       [ 17,   0],
       [ 18,   0],
       [ 19,   0],
       [ 20,   0],
       [ 21,   0],
       [ 22,   0],
       [ 23,   0],
       [ 24,   0],
       [ 25,   0],
       [ 27,   0],
       [ 28,   0],
       [ 29,   0],
       [ 30,   0],
       [ 31,   0],
       [ 56,   1],
       [ 57,   1],
       [ 58,   1],
       [ 59,   1],
       [ 60,   1],
       [ 61,   1],
       [ 62,   1],
       [ 63,   1],
       [ 64,   1],
       [ 65,   1],
       [ 66,   1],
       [ 67,   1],
       [ 68,   1],
       [ 69,   1],
       [ 70,   1],
       [ 71,   1],
       [ 95,   2],
       [ 96,   2],
       [ 97,   2],
       [100,   2],
       [101,   2],
       [102,   2],
       [103,   2],
       [104,   2],
       [105,   2],
       [106,   2],
       [108,   2],
       [109,   2],
       [110,   2],
       [111,   2],
       [113,   2],
       [114,   2],
       [135,   3],
       [137,   3],
       [138,   3],
       [139,   3],
       [141,

In [32]:
labels

array([[ 15,   0],
       [ 16,   0],
       [ 17,   0],
       [ 18,   0],
       [ 19,   0],
       [ 20,   0],
       [ 21,   0],
       [ 22,   0],
       [ 23,   0],
       [ 24,   0],
       [ 25,   0],
       [ 26,   0],
       [ 27,   0],
       [ 28,   0],
       [ 29,   0],
       [ 30,   0],
       [ 31,   0],
       [ 32,   0],
       [ 33,   0],
       [ 34,   0],
       [ 55,   1],
       [ 56,   1],
       [ 57,   1],
       [ 58,   1],
       [ 59,   1],
       [ 60,   1],
       [ 61,   1],
       [ 62,   1],
       [ 63,   1],
       [ 64,   1],
       [ 65,   1],
       [ 66,   1],
       [ 67,   1],
       [ 68,   1],
       [ 69,   1],
       [ 70,   1],
       [ 71,   1],
       [ 72,   1],
       [ 73,   1],
       [ 74,   1],
       [ 95,   2],
       [ 96,   2],
       [ 97,   2],
       [ 98,   2],
       [ 99,   2],
       [100,   2],
       [101,   2],
       [102,   2],
       [103,   2],
       [104,   2],
       [105,   2],
       [106,   2],
       [107,

In [41]:
tr

array([[750,  18],
       [659,  16],
       [223,   5],
       [388,   9],
       [428,  10],
       [794,  19],
       [736,  18],
       [793,  19],
       [780,  19],
       [462,  11],
       [ 25,   0],
       [472,  11],
       [672,  16],
       [ 31,   0],
       [379,   9],
       [106,   2],
       [299,   7],
       [102,   2],
       [784,  19],
       [712,  17],
       [593,  14],
       [193,   4],
       [514,  12],
       [222,   5],
       [587,  14],
       [625,  15],
       [786,  19],
       [380,   9],
       [656,  16],
       [337,   8],
       [314,   7],
       [590,  14],
       [461,  11],
       [393,   9],
       [738,  18],
       [430,  10],
       [785,  19],
       [267,   6],
       [422,  10],
       [589,  14],
       [624,  15],
       [301,   7],
       [ 16,   0],
       [338,   8],
       [744,  18],
       [592,  14],
       [512,  12],
       [311,   7],
       [ 97,   2],
       [269,   6],
       [431,  10],
       [469,  11],
       [788,

In [39]:
tr